name: Build and Deploy

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build-staging

      - name: Display structure of build
        run: ls -R dist_staging
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist_staging/

  deploy:
    needs: build
    runs-on: WSL

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Display structure of downloaded files
        run: ls -R

      - name: Copy build contents to server
        env:
          SSH_KEY: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.STAGING_SSH_USER }}
          SERVER_HOST: ${{ secrets.STAGING_SSH_HOST }}
        run: |
          echo "$SSH_KEY" > ssh_key
          chmod 700 ssh_key
          scp -i ssh_key -o StrictHostKeyChecking=no -r * $SERVER_USER@$SERVER_HOST:dvw-data-portal-build/dvw
          rm -r ./*

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}

      - name: SSH into instance and copy build to data-portal-dist
        env:
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            rm dvw-data-portal-build/dvw/ssh_key && \
            sudo -u uhero rm ../uhero/data-portal-backup/data-portal-dist.zip && \
            sudo -u uhero zip -r ../uhero/data-portal-backup/data-portal-dist.zip ../uhero/data-portal-dist && \
            echo "Backup successful, moving onto deployment." && \
            sudo -u uhero cp -r dvw-data-portal-build/dvw ../uhero/data-portal-dist/ && \
            sudo -u uhero cp -r ../uhero/data-portal-dist/dvw/assets/* ../uhero/data-portal-dist/assets && \
            echo "Deployment complete"
          EOF
      